# Generated by Django 4.1 on 2024-09-10 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ferrari", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("ferrari_user_permissions", "Can manage Ferrari user permissions")
                ]
            },
        ),
    ]
