# Generated by Django 5.1.1 on 2024-09-10 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ferrari", "0003_alter_client_user_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ferrari_cars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=500)),
                ("backphoto", models.ImageField(upload_to="")),
                ("price", models.IntegerField()),
                ("available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ferrari_models",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_model", models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name="client",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shoppings",
                to="ferrari.ferrari_cars",
            ),
        ),
        migrations.AddField(
            model_name="ferrari_cars",
            name="car_models",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="car_list",
                to="ferrari.ferrari_models",
            ),
        ),
        migrations.DeleteModel(
            name="Ferrari",
        ),
    ]
