# Generated by Django 5.1.1 on 2024-09-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ferrari", "0004_ferrari_cars_ferrari_models_alter_client_cart_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ferrari_models",
            name="model_desciption",
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
