# Generated by Django 5.1.1 on 2024-09-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ferrari", "0007_rename_ferrari_cars_ferrari_car_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ferrari_model",
            name="model_desciption",
            field=models.CharField(default="Ferrari", max_length=300),
        ),
    ]
