# Generated by Django 5.1.1 on 2024-09-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ferrari", "0008_alter_ferrari_model_model_desciption"),
    ]

    operations = [
        migrations.AddField(
            model_name="ferrari_model",
            name="car_cover",
            field=models.FileField(default=False, upload_to=""),
            preserve_default=False,
        ),
    ]
