# Generated by Django 5.1.1 on 2024-09-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ferrari", "0009_ferrari_model_car_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ferrari_car",
            name="backphoto",
            field=models.ImageField(upload_to="cars/"),
        ),
        migrations.AlterField(
            model_name="ferrari_model",
            name="car_cover",
            field=models.FileField(upload_to="covers/"),
        ),
    ]
