# Generated by Django 5.1.1 on 2024-09-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ferrari", "0010_alter_ferrari_car_backphoto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ferrari_model",
            name="car_cover",
            field=models.ImageField(upload_to="covers/"),
        ),
    ]
