# Generated by Django 5.1.1 on 2024-09-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ferrari", "0011_alter_ferrari_model_car_cover"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordReset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("token", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
