# Generated by Django 5.0.1 on 2024-09-14 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ferrari", "0014_passwordreset"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="costs",
        ),
    ]
