# Generated by Django 5.0.1 on 2024-09-14 02:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ferrari", "0015_remove_client_costs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Client",
            new_name="Shopping_Cart",
        ),
    ]
