# Generated by Django 5.0.1 on 2024-10-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ferrari", "0017_alter_shopping_cart_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ferrari_model",
            name="car_cover",
            field=models.ImageField(upload_to="models/"),
        ),
    ]
