upstream django {
    server backend:8000;
}

server {
    listen 80;
    server_name localhost;

    # Set maximum allowed file upload size
    client_max_body_size 100M;

    # Serve static files
    location @proxy_add {
        proxy_buffering on;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass http://django;
    }

    location / {
        try_files $uri @proxy_add;        
    }

    location /static/ {
        alias /home/app/staticfiles/;
        autoindex on;
        try_files $uri $uri/ =404;
    }
    
    # Serve media files
    location /media/ {
        alias /home/app/media/;
        autoindex on;
        try_files $uri $uri/ =404;
    }

}
